#pragma once

enum TEAMTYPE { NORTH, SOUTH, TEAM_END };
enum OBJTYPE { OBJECT, OBJECT_BUILDING, OBJECT_CHARACTER, OBJECT_BULLET, OBJECT_ARROW };
enum OWNER { NONE };

enum COL { D, RD, R, RU, U, LU, L, LD };